### ISSUE TITLE
Question regarding upstream work (OpenVPN)

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#10]
What patches do you use for OpenVPN and do you actively upstream them into OpenVPN so that others can benefit as well?

**Comment by jpwhiting** [comment]
The only patches to openvpn we use are the Tunnelblick patches that openvpn community decided they do not want to merge in.

**Comment by baimafeima** [comment]
@jpwhiting Do I understand it correctly then that - when building Safejumper from source on a Linux-based operating system - that I must use your custom openVPN? Or is there a possibility to simply use my local openVPN (without the Tunnelblick patches) as a dependency to Safejumper?

**Comment by jpwhiting** [comment]
If you use your own openvpn without the tunnelblick patches then a few protocols will fail to work at all. Namely ECC+XOR and ECC. Both of those use options in the .ovpn files that vanilla openvpn doesn't understand.

**Comment by baimafeima** [comment]
Thanks for the updates! I definitely need to rely on ECC+XOR here in China, otherwise openVPN traffic will be detected by DPI. Unfortunately, there is currently still no possibility to use Safejumper on Solus due to a missing snap release.

**Comment by jpwhiting** [comment]
No worries. The linux zip file doesn't work on Solus for some reason? Once I get some other fixes/features into Safejumper I can probably take a look at doing a snap release, I'm surprised none of the existing options work though. I thought the zip file covered all the non .deb and non .rpm based distributions.

**Comment by baimafeima** [comment]
Yeah, the linux zip file doesn't work. I tried both the Safejumper and the Safejumper.sh file - and while the application launches, it only does so with over five or six superuser access requests and in between trying to change locations and nodes. When changing encryption to Tor + Scramblesuit the application crashes. The other options are clickable but no connection can be made and I've tested around 10 different locations. A mere executable is also not ideal in terms of user friendliness, unsafe to execute in general, and it also won't create a menu entry in the start menu so a user always has to navigate to the downloaded folder and click on the executable to run the programme. Unless there is a `snap` package I am unable to continue to use the application and help with testing, unfortunately.

**Comment by baimafeima** [comment]
> I thought the zip file covered all the non .deb and non .rpm based distributions.

.`deb` and .`rpm` files are legacy file formats and in my view there is no reason in supporting them any longer or waste resources on them. Both Ubuntu and Fedora have adopted `snaps` and `flatpaks` for easy cross-platform installation, even beyond the two operating systems.
