### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#11]
Could you tag the releases here on GitHub so the changelog and the commits become visible?

**Comment by jpwhiting** [comment]
All tags have been pushed to the public git repository.

**Comment by baimafeima** [comment]
@jpwhiting What I meant is to make the changelog directly visible in the GitHub releases. This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.
