### ISSUE TITLE
Links to upstream proxy/tunnels

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#12]
When using the OpenVPN Configuration Generator via your website, there is an advanced box offering the following five additional proxy/tunnel options: 
- http
- socks
- tor 
- ecc
- xor
Your desktop application Safejumper has Tor, ECC and Xor included, however, they are not included in the OpenVPN client and, I assume, must be installed locally on the operating system first. Could you provide me links to the upstream source code (GitHub, etc.) of these three projects?

**Comment by jpwhiting** [comment]
We use the tunnelblick patches on openvpn to add those protocols. More about these patches can be found here: https://tunnelblick.net/cOpenvpn_xorpatch.html The patches themselves are here: https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.4.4/patches
