### ISSUE TITLE
Add changelog to GitHub

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#13]
Could you add the changelog to your GitHub releases? Distribution maintainers would probably not want to include every build (any chance you could add actual versioned releases from time to time, not just builds to indicate this?) but clearly and efficiently see what has changed. This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by proxysh** [comment]
Sounds like a good idea, but I am not sure it comes handy on the long run. Since several developers may work on the project, not everyone may have time to use the generator code. Plus, the changelog really is available already there: https://github.com/proxysh/Safejumper-for-Desktop/commits/master

**Comment by baimafeima** [comment]
Yeah, but the actual problem I see is that you just release builds and don't have versioned releases. There are still many roadblocks to get it included into the repository of my operating system of choice: https://dev.solus-project.com/T2428

**Comment by proxysh** [comment]
Fully understood. We'll try to consider it if there is more demand. But we also have to focus on what matters for the most. I hope you'll understand.
