### ISSUE TITLE
Thatoneprivacysite.net review

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#14]
There is no comprehensive, independent review of your VPN service as of now, but https://thatoneprivacysite.net/vpn-comparison-chart/ has given a good overview. I'd recommend to get in touch with thatoneprivacysite [here](https://thatoneprivacysite.net/contact-info/) at your earliest convenience to improve your service. 

Regarding your logging policy, it looks like you do not log traffic. Could you clarify the following `missing points` regarding your service: 
- Logs DNS requests (yes/no)
- Logs Timestamps (yes/no)
- Logs Bandwidth (yes/no)
- Logs IP Adresses (yes/no)

Would you also consider the following: 
- Privacy: Anonymous signup without email (anonymous tokens after you signed up via email don't count)
- Privacy: Anonymous cash payment
- Security: Make PGP key available
- Security: Leak Protection: IPv6 (supported/blocked)
- Obfuscation: Support TCP Port 443
- Obfuscation: Support openconnect
- Obfuscation: Support obfs4 (not just the legacy obfsproxy or scramblesuit)
- Obfuscation: Support SSH tunneling
- Obfuscation: Support SSL tunneling via Stunnel
- Website: Free your website of proprietary APIs (the googleapis slow down the page and make it inaccessible)
- Security: Improve server SSL rating to a mininum of A
- Website: Clean up your website (looks too bloated and sensationalist, make it simple, white, non-flickering)
- Pricing: Offer at minimum a 7-day money back guarantee or a 3-hour free token to test your services
- Policies: Drop affiliate marketing or if you choose not to do so, make it as transparent as possible (full disclosure requirements)

**Comment by proxysh** [comment]
Hello,

We won't contact this site, but you should feel free to do so. We cannot be responsible if they publish biased or inaccurate content.

As for your inquiries, here are our answers.

Logs DNS requests (yes/no) => No
Logs Timestamps (yes/no) => No
Logs Bandwidth (yes/no) => No
Logs IP Adresses (yes/no) => No
Privacy: Anonymous signup without email (anonymous tokens after you signed up via email don't count) => Coming next week, hehe :)
Privacy: Anonymous cash payment => We'd be happy to team up with anyone receiving cash on our behalf. Would you do that? 
Security: Make PGP key available => Already the case, check https://paste.proxy.sh/?1a8c8de3f427406b#+H9X/m1jE7T7pJusCOsHmr4PbVXjY+rBf72oGe3fD50= - should we publish it somewhere, make a special page about it?
Security: Leak Protection: IPv6 (supported/blocked) => Please check leaktest.online, that's the tool we built. It checks Ipv6. And Safejumper, our OpenVPN client, has a built-in option to disable your OS' IPv6.
Obfuscation: Support TCP Port 443 => It's already the case. You should open a support ticket to our engineering unit from your Proxy.sh account for more details.
Obfuscation: Support openconnect => It's already the case. You should open a support ticket to our engineering unit from your Proxy.sh account for more details.
Obfuscation: Support obfs4 (not just the legacy obfsproxy or scramblesuit) => Work in progress, this one is vey difficult to achieve but we're on it along with other open source OpenVPN developers.
Obfuscation: Support SSH tunneling => It's already the case. You should open a support ticket to our engineering unit from your Proxy.sh account for more details.
Obfuscation: Support SSL tunneling via Stunnel => It's already the case. You should open a support ticket to our engineering unit from your Proxy.sh account for more details.
Website: Free your website of proprietary APIs (the googleapis slow down the page and make it inaccessible) => We really would like to retain the Google Translate option, it's very useful for many of our customers. And you can just disable JavaScript or bypass our frontend pages. Our website has nothing to do with our VPN network.
Security: Improve server SSL rating to a mininum of A => It's already the case. You may open a support ticket to our engineering unit if you have a contradictory test.
Website: Clean up your website (looks too bloated and sensationalist, make it simple, white, non-flickering) => Sorry that you do not like it, we do like it the way it is.
Pricing: Offer at minimum a 7-day money back guarantee or a 3-hour free token to test your services => We already provide money back guarantee on any purchase if you pay us with PayPal or a payment method where a refund is costless.
Policies: Drop affiliate marketing or if you choose not to do so, make it as transparent as possible (full disclosure requirements) => We only have a simple affiliate system and it's already fully transparent. Not sure what you mean by full disclosure. 

Should you have any further question, please do not hesitate.
