### ISSUE TITLE
Offer additional tarball without patches

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#15]
The only chance to get Safejumper included into the repositories of my operating system of choice, Solus, is to offer versioned tarballs which do not include any patches to openVPN but instead have listed openVPN as a dependency so that the locally supported openVPN as part of the operating system is used as default. As many users would still need the patches for various reasons, I think it would be great to offer two tarball versions with each tagged release, one without and one with. 

In the long run, I think only tarballs without any openVPN patches should be released and the version with patches be made available as a snap package. Then, both versions could actually be included into many official distributions. The `non-patched tarball version` via locally built native packages (which rely on dependencies met by the operating system itself) and a `patched snap version` to which the proxy.sh team can push silent updates so any user is automatically updated (if they so choose).

**Comment by proxysh** [comment]
Sadly, we need our special version of OpenVPN to connect to our network using protocols such as ECC, XOR, TLS-Crypt and more. Providing two versions will be too much unnecessary work for us. It is far easier for users to use custom OpenVPN setups depending on their most exotic environment. That is to say, the share of Proxy.sh users on the same OS as you is very, very thin.

**Comment by baimafeima** [comment]
> It is far easier for users to use custom OpenVPN setups depending on their most exotic environment.

In the meantime, until a snap is ready, would you consider providing a guide on your website on how to use Safejumper for Solus and `NetworkManager Applet`, the notification area applet for managing network devices and connections?

**Comment by jpwhiting** [comment]
Safejumper can't be used with NetworkManager, they are separate applications completely. Both happen to be able to manipulate openvpn, but otherwise they are completely separate.

**Comment by baimafeima** [comment]
Ah, I meant how to connect to your servers of course and not the Safejumper application. Is there a possibility to add some instructions to your website for using your VPN network with NetworkManager Applet?

**Comment by jpwhiting** [comment]
https://proxy.sh/tutorial/openvpn-linux.html <-- this isn't enough? Seems pretty straightforward to me.

**Comment by proxysh** [comment]
Jeremy is right. Our Linux tutorial is valid for all Linux distribs; there might be few differences in UI/UX but overall it is the exact same procedure.

**Comment by baimafeima** [comment]
> Sadly, we need our special version of OpenVPN to connect to our network using protocols such as ECC, XOR, TLS-Crypt and more.

Just a thought: Wouldn't it be possible to offer ECC, XOR, TLS-Crypt as separate modules which could be packaged by distribution maintainers - thereby modularizing Safejumper - while keeping OpenVPN unaltered?

**Comment by jpwhiting** [comment]
No, these options are patches to openvpn itself. Openvpn doesn't support plugins or modules for this sort of change so that wouldn't work.
