### ISSUE TITLE
safejump crash

### ISSUE THREAD

**Issue by theot71** [proxysh/Safejumper-for-Desktop#16]
i have crash with safe jump vpn software from https://proxy.sh, i am using Linux Mint 18.3 "Sylvia" - Cinnamon (64-bit) this is the crash rapport. what must i do?
GDB Log                                                           
===================================================================
[New LWP 4793]
[New LWP 4796]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/safejumper/safejumper'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb0b4818428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb0b87d0780 (LWP 4793))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 4793]
[New LWP 4796]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/safejumper/safejumper'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb0b4818428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb0b87d0780 (LWP 4793))]
#0  0x00007fb0b4818428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fb0b481a02a in __GI_abort () at abort.c:89
#2  0x000000000100af39 in ?? ()
#3  0x000000000100710e in ?? ()
#4  0x0000000001001990 in ?? ()
#5  0x00000000004f9717 in ?? ()
#6  0x00000000004f9f52 in ?? ()
#7  0x0000000000a9854f in ?? ()
#8  0x0000000000add2a8 in ?? ()
#9  0x0000000000add218 in ?? ()
#10 0x0000000000a96970 in ?? ()
#11 0x00000000008c5b35 in ?? ()
#12 0x00000000008c6213 in ?? ()
#13 0x00000000008cfdcc in ?? ()
#14 0x00000000008bd5d5 in ?? ()
#15 0x0000000000db143d in ?? ()
#16 0x0000000000db107a in ?? ()
#17 0x0000000000aa0cb6 in ?? ()
#18 0x0000000000aa1d71 in ?? ()
#19 0x0000000000aa1e8a in ?? ()
#20 0x00000000004878de in ?? ()
#21 0x00000000011dd3de in ?? ()
#22 0x0000000000aa1f92 in ?? ()
#23 0x0000000000488002 in ?? ()
#24 0x0000000000487fe3 in ?? ()
#25 0x0000000000417d08 in ?? ()
#26 0x000000000044e42d in ?? ()
#27 0x00007fb0b4803830 in __libc_start_main (main=0x44e387, argc=1, argv=0x7ffef2550c78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffef2550c68) at ../csu/libc-start.c:291
#28 0x0000000000415779 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 4793]
[New LWP 4796]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/safejumper/safejumper'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb0b4818428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb0b87d0780 (LWP 4793))]

Thread 2 (Thread 0x7fb0b075e700 (LWP 4796)):
#0  0x00007fb0b48de70d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007fb0b696cc62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#2  0x00007fb0b696e8d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
No symbol table info available.
#3  0x00000000008c8a8c in ?? ()
No symbol table info available.
#4  0x00000000010190f3 in ?? ()
No symbol table info available.
#5  0x00007fb0b54556ba in start_thread (arg=0x7fb0b075e700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fb0b075e700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140396851488512, -5282363363434459589, 0, 140732964077839, 140396851489216, 0, 5318793395260591675, 5318799576000990779}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007fb0b48ea3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7fb0b87d0780 (LWP 4793)):
#0  0x00007fb0b4818428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 4793
        selftid = 4793
#1  0x00007fb0b481a02a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 140732964077216, 4291548, 4065656464, 23645024, 140732964077280, 16821907, 140732964077248, 4291359, 140732964077664, 4294967295, 140732964077392, 140732964077664, 3, 140396923098992, 140396986173312}}, sa_flags = 4288290, sa_restorer = 0x3c28290}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000000000100af39 in ?? ()
No symbol table info available.
#3  0x000000000100710e in ?? ()
No symbol table info available.
#4  0x0000000001001990 in ?? ()
No symbol table info available.
#5  0x00000000004f9717 in ?? ()
No symbol table info available.
#6  0x00000000004f9f52 in ?? ()
No symbol table info available.
#7  0x0000000000a9854f in ?? ()
No symbol table info available.
#8  0x0000000000add2a8 in ?? ()
No symbol table info available.
#9  0x0000000000add218 in ?? ()
No symbol table info available.
#10 0x0000000000a96970 in ?? ()
No symbol table info available.
#11 0x00000000008c5b35 in ?? ()
No symbol table info available.
#12 0x00000000008c6213 in ?? ()
No symbol table info available.
#13 0x00000000008cfdcc in ?? ()
No symbol table info available.
#14 0x00000000008bd5d5 in ?? ()
No symbol table info available.
#15 0x0000000000db143d in ?? ()
No symbol table info available.
#16 0x0000000000db107a in ?? ()
No symbol table info available.
#17 0x0000000000aa0cb6 in ?? ()
No symbol table info available.
#18 0x0000000000aa1d71 in ?? ()
No symbol table info available.
#19 0x0000000000aa1e8a in ?? ()
No symbol table info available.
#20 0x00000000004878de in ?? ()
No symbol table info available.
#21 0x00000000011dd3de in ?? ()
No symbol table info available.
#22 0x0000000000aa1f92 in ?? ()
No symbol table info available.
#23 0x0000000000488002 in ?? ()
No symbol table info available.
#24 0x0000000000487fe3 in ?? ()
No symbol table info available.
#25 0x0000000000417d08 in ?? ()
No symbol table info available.
#26 0x000000000044e42d in ?? ()
No symbol table info available.
#27 0x00007fb0b4803830 in __libc_start_main (main=0x44e387, argc=1, argv=0x7ffef2550c78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffef2550c68) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -5282365127189623237, 4282192, 140732964080752, 0, 0, 5281774755760016955, 5318803397399514683}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x44e387}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#28 0x0000000000415779 in ?? ()
No symbol table info available.
#0  0x00007fb0b4818428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fb0b481a02a in __GI_abort () at abort.c:89
#2  0x000000000100af39 in ?? ()
#3  0x000000000100710e in ?? ()
#4  0x0000000001001990 in ?? ()
#5  0x00000000004f9717 in ?? ()
#6  0x00000000004f9f52 in ?? ()
#7  0x0000000000a9854f in ?? ()
#8  0x0000000000add2a8 in ?? ()
#9  0x0000000000add218 in ?? ()
#10 0x0000000000a96970 in ?? ()
#11 0x00000000008c5b35 in ?? ()
#12 0x00000000008c6213 in ?? ()
#13 0x00000000008cfdcc in ?? ()
#14 0x00000000008bd5d5 in ?? ()
#15 0x0000000000db143d in ?? ()
#16 0x0000000000db107a in ?? ()
#17 0x0000000000aa0cb6 in ?? ()
#18 0x0000000000aa1d71 in ?? ()
#19 0x0000000000aa1e8a in ?? ()
#20 0x00000000004878de in ?? ()
#21 0x00000000011dd3de in ?? ()
#22 0x0000000000aa1f92 in ?? ()
#23 0x0000000000488002 in ?? ()
#24 0x0000000000487fe3 in ?? ()
#25 0x0000000000417d08 in ?? ()
#26 0x000000000044e42d in ?? ()
#27 0x00007fb0b4803830 in __libc_start_main (main=0x44e387, argc=1, argv=0x7ffef2550c78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffef2550c68) at ../csu/libc-start.c:291
#28 0x0000000000415779 in ?? ()

**Comment by jpwhiting** [comment]
Hi there,

I'm unable to recreate this crash here on a fresh linux mint 18.3 64 bit cinnamon vm. Which safejumper package did you install? Did you install the dependency libxcb-xinerama0 ? I had to install that here to get safejumper build 81 amd64 deb to install since it's a dependency.

**Comment by jpwhiting** [comment]
Fixed in build 82 coming shortly. Reopen if you hit this again please.
