### ISSUE TITLE
OpenVPN installs to $INSTDIR, but PathHelper::openvpnFilename() returns a static path

### ISSUE THREAD

**Issue by ryanbentleyxz** [proxysh/Safejumper-for-Desktop#17]
This results in SafeJumper not being able to locate the OpenVPN binary if you have chosen a non-traditional install directory during the NSIS install.

A fix would be to use the resourcesPath() method
`#ifdef Q_OS_WIN
    return resourcesPath() + "/OpenVPN/bin/openvpn.exe";
#else	// Q_OS_LINUX`

**Comment by jpwhiting** [comment]
Hello,

Yeah, I'll have this fixed in the next build no problem.

thanks,
Jeremy

**Comment by jpwhiting** [comment]
I've fixed this in git, it will be in build 82

**Comment by jpwhiting** [comment]
Fixed in build 82 coming soon. Reopen if you hit this issue again.
