### ISSUE TITLE
ipv6 leaks with Safejumper

### ISSUE THREAD

**Issue by ma-wittmann** [proxysh/Safejumper-for-Desktop#18]
Hello,

I have to report that your ipv6 leak protection is not working and your ipv6 leak test on https://leaktest.online/ipv6/ is not reliable.
I activated ipv6 leak protection in Safejumper settings. Ipv6 leak test on https://leaktest.online/ipv6/ tells me that everything is fine. But all other common ipv6 leak test tools reveal my ipv6 adress!
Please test it by yourself on:
https://www.dein-ip-check.de/
http://ipv6-test.com/
https://ip6.nl/

I have used different VPN providers before (Windscribe, tigerVPN, VPN Unlimited, Safer VPN).
With these VPNs ipv6 was automatically disabled when connected and automatically turned on again when closing VPN client.
I'm very disappointed with Safejumper because of the non-functional ipv6 leak protection!
I know how to disable ipv6 completely - but I don't want this. I'm using ipv6 but when starting VPN client ipv6 must automatically disabled due to privacy concerns. Unfortunately this is not working in Safejumper.

Could you please fix this in near future?

Kind Regards
Matthias

**Comment by proxysh** [comment]
Thanks for your feedback. What is your operating system & version and do you have more details to share? 

Leaktest.online test is something different, we'll make sure it is fixed up.

**Comment by ma-wittmann** [comment]
Hello,

 

I'm using Windows 10 x64, latest build.

Ipv6 leaks tested on 2 notebooks with same results - ipv6 adress is revealed by ipv6 leaktest tools.

 

I already sent screenshots of this issue to your support. Due to the ipv6 leaks I'm using SaferVPN now which disables ipv6 when connected to one of their servers.

I will wait for a new update of Safejumper fixing this issue before using it again.

 

Kind Regards

Matthias

 

 

 

Gesendet: Sonntag, 21. Januar 2018 um 12:11 Uhr
Von: "Proxy.sh" <notifications@github.com>
An: proxysh/Safejumper-for-Desktop <Safejumper-for-Desktop@noreply.github.com>
Cc: ma-wittmann <ma-wittmann@web.de>, Author <author@noreply.github.com>
Betreff: Re: [proxysh/Safejumper-for-Desktop] ipv6 leaks with Safejumper (#18)


Thanks for your feedback. What is your operating system & version and do you have more details to share?

Leaktest.online test is something different, we'll make sure it is fixed up.

**Comment by 0xffffe001** [comment]
Hey there @proxysh team!
Can you please let us know if there is any update?
p.s
I'm experiencing same "trouble".

**Comment by proxysh** [comment]
Are you referring to Safejumper on Windows and Ipv6? There is a new version coming soon from @jpwhiting -- stay tuned.

**Comment by jpwhiting** [comment]
Fix is included in upcoming build 82. Reopen if you still hit it with this build.
