### ISSUE TITLE
Exec as root fails

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#2]
![ubuntumateerror](https://cloud.githubusercontent.com/assets/23112309/21669503/3305e642-d347-11e6-814e-10ae3616763f.png)
When trying to connect in Ubuntu MATE I get the following error message: 
Exec as root fails. result code = 100

**Comment by threemonkeys** [comment]
Thanks for the heads up. A new patch is coming soon that will solve this issue.

**Comment by proxysh** [comment]
Thanks for the heads up. A new patch is coming soon that will solve this issue.

**Comment by baimafeima** [comment]
Thank you for responding to this so quickly and I look forward to a new release.

**Comment by proxysh** [comment]
Anytime ;)
