### ISSUE TITLE
Support tickets cannot be sent

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#3]
It appears that your website is not configured properly. When trying to send a support ticket, I get the following error message. Please keep this issue open. I will confirm once it is solved. 
![secure connection failed](https://cloud.githubusercontent.com/assets/23112309/21963433/9a9d2f6e-db75-11e6-9aec-72e244babb51.png)

**Comment by proxysh** [comment]
On what page did you encounter that?

**Comment by baimafeima** [comment]
This issue is solved. It apparently resulted from another insecurely configured server I have used. Not related to your service.

**Comment by proxysh** [comment]
Ok.
