### ISSUE TITLE
Safejumper crashes in Ubuntu MATE

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#4]
The application crashes upon launch.

**Comment by proxysh** [comment]
Please kindly go through https://proxy.sh/contact and submit the crash report or any log there. Thanks :)

**Comment by baimafeima** [comment]
No, as I am unable to even start the application. Hence, I cannot provide any crash reports.

**Comment by proxysh** [comment]
Well, there might still be some debug logs left in the Safejumper or /tmp folder. Please double check. Please also reach out to us at ./contact about specific issues such as this one.

**Comment by baimafeima** [comment]
This is from the debug log: 
```
Starting Application
StartDwnl_OldIp() attempt 1
WHICH OBFS #
IsObfsInstalled FALSE
InstallObfs() in
Executing as root. Cmd = apt-get args = update
```

**Comment by jpwhiting** [comment]
Ok, which build of Safejumper are you using and which version of Ubuntu Mate? I'll take a look at finding the cause and fixing it this week once I know both of those.

**Comment by proxysh** [comment]
Thanks for the debug, making sense. Please let us know your Mate version as Jeremy suggested and we'll take a look at it.

**Comment by baimafeima** [comment]
```
Ubuntu 16.04.2 LTS
MATE 1.16.1
Safejumper v3.2 alpha, build 73
```
I am using the Ubuntu MATE community spin with the MATE desktop environment.

**Comment by proxysh** [comment]
Thanks for the heads up.

**Comment by jpwhiting** [comment]
@baimafeima are you on a 64 bit or 32 bit OS? Here I get a segfault/crash in safejumper if I am missing some of the dependencies like libxcb-render-util0 for the right architecture (i.e. if I have the 32 bit safejumper installed, but no 32 bit libraries)

Can you tell me the output of ldd /opt/safejumper/safejumper and file /opt/safejumper/safejumper ?

**Comment by baimafeima** [comment]
Sure, I am using the 64-bit OS.

```
	linux-vdso.so.1 =>  (0x00007ffce3f75000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f83140ba000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007f8313eb6000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f8313cab000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007f8313aa6000)
	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007f83138a1000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f8313699000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f8313491000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f831328d000)
	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007f831307e000)
	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007f8312e7a000)
	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007f8312c77000)
	libxcb-xinerama.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinerama.so.0 (0x00007f8312a73000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f8312871000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f831264f000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f831240b000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f8312161000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8311e27000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1 (0x00007f8311bf2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f83119d8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f83117d4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f83115cb000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f8311357000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f831113a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8310db7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8310aae000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8310898000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f83104ce000)
	/lib64/ld-linux-x86-64.so.2 (0x000055fd0e428000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007f83102c8000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f83100c3000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f830febd000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f830fc94000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f830fa6e000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f830f869000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f830f666000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f830f462000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f830f25f000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f830f051000)
	libwayland-server.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f830ee3f000)
	libgbm.so.1 => /usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f830ec31000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f830ea22000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f830e7f2000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f830e5e0000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f830e3dd000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f830e1d6000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f830dfd0000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f830ddc7000)
```

`/opt/safejumper/safejumper: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=c10418dca7c906860111f7d848a206fab3483d23, stripped`

**Comment by jpwhiting** [comment]
Hello, I just set up a Ubuntu mate 16.04 64 bit vm and safejumper works ok on it when using rsa or ecc encryption. However when switching to obfs encryption it tries to install obfsproxy and fails because of a missing compiler. I'll add obfsproxy locally to the safejumper package on linux for build 74 but for now if you install gcc the installation of obfsproxy should complete.

If you're getting a different crash somewhere else, can you tell me which part of Safejumper's process it is at when it crashes? Logging in, connecting, if connecting, which encryption type are you using etc.

**Comment by baimafeima** [comment]
Please let me know once build 74 lands. I've just had a SIGSEGV notice upon initial startup of Safejumper.

**Comment by baimafeima** [comment]
I cannot access the _Settings_ menu and when trying to, the application freezes. Without accessing the settings menu I cannot change the encryption options.

**Comment by proxysh** [comment]
Thanks for the heads up.

**Comment by jpwhiting** [comment]
Hmm, I'll take a look at the feezing issue here and see if I can recreate it. I almost have build 74 ready, just need to sort out the "Connect to" menu being empty and see if the server guy has fixed scramblesuit on the servers.

**Comment by baimafeima** [comment]
I tried with the latest build 74 but I cannot get passed the superuser authentication.

**Comment by proxysh** [comment]
Could you please elaborate?

**Comment by jpwhiting** [comment]
The first time you run safejumper after installation of a new package it runs a few commands as root to change the owner of the executables. So there are 3 or 4 pkexec dialogs that show up in a row on the first run. Once you get through all 4 of them (each should show it is running a different command also by the way) it should be good to go. Did you get through all of them?

**Comment by baimafeima** [comment]
> Did you get through all of them?

I have no way to distinguish them. All I can say is that the application froze once I had to key in my superuser password and is currently unusable in Ubuntu MATE. I used the .deb file.

**Comment by jpwhiting** [comment]
Hmm, maybe the MATE ui for pkexec doesn't show what command it's trying to execute? At any rate, could you send me the logs and I'll see if I can recreate it here. I tried a few times on Ubuntu MATE here and was not able to get it to hang.
