### ISSUE TITLE
App logs & SSD

### ISSUE THREAD

**Issue by xxblx** [proxysh/Safejumper-for-Desktop#6]
Safejumper writes to disk too many openvpn logs and debug logs until running. It writes every second new data to disk. That may be not good for SSD. 
How about to do optional logging with enable/disable checkboxes in app settings? 

I got proxy.sh and want to use SafeJumper app with it. But so often write-on-disk operations looks terrible for SSD in my laptop. I think other users with SSD will have same things about it.

**Comment by jpwhiting** [comment]
I think that should be doable. Safejumper is watching OpenVPN in two ways, by watching it's logfile and by connection on a local socket. I'll need to test to be sure but I think we could get by with just the socket communication if needed. 

We could definitely have a switch to turn off the debug log also.

**Comment by xxblx** [comment]
Sounds good. 
Also I think would be pretty add optional parameter - time interval for writing logs like that done in modern web browsers for cache writing on disk. 
Right now SafeJumper write every second, so parameter by default is 1. If user set it's value to 60 then logs writes on disk once per 60 seconds. 

p.s. gzip compressing for logs before on-disk write shall powerfully decrease size of written data too

**Comment by jpwhiting** [comment]
The upcoming build 77 adds an option for disabling logging. This disables writing to ~/.safejumper/safejumper-debug.log completely and also adding log entries to the log screen. It doesn't disable openvpn's logging to ~/.safejumper/safejumper-openvpn.log though. We will look into that in another build later on.

**Comment by xxblx** [comment]
Great. 
Thanks!

**Comment by proxysh** [comment]
Build 77 is now out and you shall enjoy smaller logs, as well as an option to disable them altogether.
