### ISSUE TITLE
Hide login name by default

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#8]
Currently, the login window shows the login name in clear letters. As I frequently need to share my screen via a projector, this is a less than ideal situation. I prefer it to be hidden by default with an option to reveal the login name (not the password) by ticking a button.

**Comment by proxysh** [comment]
Thanks for the heads up, but we will discard this request. There is no sufficient appeal for our entire user base and we have better priorities, such as making openvpn a system service. Thanks for your comprehension and please feel free to suggest more.

**Comment by baimafeima** [comment]
@proxysh What about making it optional to hide user/log in credentials?

**Comment by proxysh** [comment]
We are happy to reconsider your request following higher user demand for this, and we will hide the login name in a future update :)
