### ISSUE TITLE
Add screenshots here on GitHub

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Desktop#9]
I think it would be great to add screenshots here on your GitHub page as your main website is not accessible in regions affected by censorship. Potential users could then get a better idea of how your software looks like.

**Comment by proxysh** [comment]
You can upload the screenshots here and we will update them to the README, no problem. You can even suggest a whole improvement of the README itself, with better wording.

**Comment by baimafeima** [comment]
It's better if you upload screenshots as the main window will show private user data.

**Comment by proxysh** [comment]
Yes, we will re-upload them ourselves, but please provide them here so we can make use of them.
